# adapted from https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
version: '3'

services:
  signaling-server:
    build: ./signaling-server
    restart: always
    environment:
      - HTTP_PORT=3000
      - VIRTUAL_HOST= connect.merzlabs.de
      - LETSENCRYPT_HOST=connect.merzlabs.de
      - LETSENCRYPT_EMAIL=info@merzlabs.de

  app:
    build: ./test-app
    restart: always
    volumes:
      - app:/usr/local/apache2/htdocs/
    environment:
      - HTTP_PORT=80
      - VIRTUAL_HOST= connect.merzlabs.de
      - LETSENCRYPT_HOST=connect.merzlabs.de
      - LETSENCRYPT_EMAIL=info@merzlabs.de
    networks:
      - proxy-tier
      - default

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  app:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
